### ISSUE TITLE
Proposal for a B.1.3 sublineage potentially associated with recent outbreaks in East Asia (45 sequences)

### ISSUE THREAD

**Issue by c19850727** [mpxv-lineages/lineage-designation#32]
![image](https://github.com/mpxv-lineages/lineage-designation/assets/86835836/a9e6efdb-7dd3-429d-a6fb-9462da03d6f0)

### Description
**Sublineage of**: B.1.3
**Earliest sequence**: 2022/09 (Japan-Tokyo)
**Most recent sequence**: 2023/06/15 (China-Zhejiang)

This proposed sublineage of B.1.3 is defined by nuc mutation G109523A.

There are up to now 45 sequences, mainly from Japan-Tokyo (39 seqs), and also from Japan-Osaka (1 seq), Taiwan (4 seqs) and China-Zhejiang (1 seq).

It makes up for 42/48 sequences collected in Asia since January 1st 2023.

### Genomes:
EPI_ISL_17959216, EPI_ISL_17445514, EPI_ISL_17959214, EPI_ISL_17959215, EPI_ISL_17445517, EPI_ISL_17809521, EPI_ISL_17445518, EPI_ISL_17445515, EPI_ISL_17445516, EPI_ISL_17445519, EPI_ISL_17428283, EPI_ISL_17592666, EPI_ISL_17592667, EPI_ISL_17592668, EPI_ISL_17817239, EPI_ISL_17837266, EPI_ISL_17592669, EPI_ISL_17837267, EPI_ISL_16905443, EPI_ISL_17837268, EPI_ISL_16905444, EPI_ISL_17592665, EPI_ISL_17152764, EPI_ISL_16905442, EPI_ISL_17152843, EPI_ISL_17428286, EPI_ISL_17762484, EPI_ISL_17762485, EPI_ISL_17008293, EPI_ISL_17665625, EPI_ISL_17722468, EPI_ISL_17008294, EPI_ISL_17665626, EPI_ISL_17008295, EPI_ISL_17665627, EPI_ISL_17008296, EPI_ISL_17518107, EPI_ISL_17665624, EPI_ISL_17246657, EPI_ISL_17246659, EPI_ISL_17692268, EPI_ISL_17817240, EPI_ISL_17592670, EPI_ISL_17817241, EPI_ISL_17692269

**Comment by AngieHinrichs** [comment]
INSDC sequences (there's also one from Belgium now; unfortunately none from mainland China):
```
Japan/Tokyo/2022/TKY220165	LC753968.1	2022-09
Japan/Tokyo/2022/TKY220187	LC753970.1	2022-10
Japan/Tokyo/2022/TKY220176	LC753969.1	2022-10
Belgium/UZ_REGA_122/2022	OR035728.1	2022-10-28
Taiwan/110-093831/2023	OQ581853.1	2023-02
Taiwan/240031000030/2023	OQ721952.1	2023-03
Japan/Tokyo/2023/TKY220310	LC756922.1	2023-01-25
Japan/Tokyo/2023/TKY220318	LC756923.1	2023-01-25
Japan/Tokyo/2023/TKY220343	LC760461.1	2023-02-13
Japan/Tokyo/2023/TKY220325	LC756924.1	2023-01-30
Japan/Tokyo/2023/TKY220304	LC760460.1	2023-01-23
Japan/Tokyo/2023/TKY220342	LC756925.1	2023-02-09
Taiwan/110-539498/2023	OQ721954.1	2023-03
Taiwan/0310000009/2023	OQ581855.1	2023-03
```
Branch of UShER hMPXV tree (INSDC-only):
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/mpxv_lineage-designation-32.json?c=gt-nuc_105923&label=id:node_408
<img width="992" alt="image" src="https://github.com/mpxv-lineages/lineage-designation/assets/186983/e37fdfc7-87ac-4875-beb5-3efdf2d15a58">

This example helped uncover a bug for reverse strand genes in my logic that handles multiple nucleotide substitutions in the same codon -- it's fixed on dev.usher.bio, but the fix won't propagate to usher.bio for the next couple weeks.  So for MPXV, please use dev.usher.bio instead of usher.bio for the next couple weeks.

**Comment by corneliusroemer** [comment]
This has been on my backlog for a while, thanks for the proposal and reminder @c19850727!
