### ISSUE TITLE
Proposal for B.1.6 sublineage OPG025:A21T,E34K and others

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [mpxv-lineages/lineage-designation#41]
**Description**

Potential new hMPXV B.1.6.* lineage identified in Peru by the *Genomic Surveillance of the Instituto Nacional de Salud (INS-Peru)*. Lineage is defined by numerous mutations, deletions and stop codon as follows: 

**OPG019: Q81stop**
**OPG025: A21T, E34K**
**OPG121: S65L**
**OPG153: D385del**
**OPG210: S1590F**

**Genomes**

Earliest sequence: 2023-07-12
Most recent sequence: 2024-06-01

**Countries circulating**

Major clade: Peru (92 genomes)

**GISAID codes**

[EPICodes.txt](https://github.com/user-attachments/files/16731640/EPICodes.txt)

**Evidence**

**1. Global Phylogeny**
![new_clade_B 1 6](https://github.com/user-attachments/assets/56304645-ca58-4b5f-9678-de109baa0e35)

**2. New Clade**
![detail](https://github.com/user-attachments/assets/af1f8979-5a1c-4ce4-bb3b-c9dd9c4d0176)

**3. Alignment**
![mutations](https://github.com/user-attachments/assets/6260e503-110f-4a8c-835e-fb7be1b5f880)

**Comment by ammaraziz** [comment]
@Vjimenez-vasquez are you able to submit these to ncbi/genbank?

**Comment by Vjimenez-vasquez** [comment]
> @Vjimenez-vasquez are you able to submit these to ncbi/genbank?

> Hi @ammaraziz, we will discuss the submission to NCBI/genbank in the INS-PERU team

**Comment by Wen1953** [comment]
Designated as **B.1.6.1**, 78 genomes in GISAID so far.
![Captura desde 2024-10-21 08-54-36](https://github.com/user-attachments/assets/f61c9779-875b-493c-8984-d4af57289c71)

**Comment by Vjimenez-vasquez** [comment]
> Designated as **B.1.6.1**, 78 genomes in GISAID so far. ![Captura desde 2024-10-21 08-54-36](https://private-user-images.githubusercontent.com/89021119/378456628-f61c9779-875b-493c-8984-d4af57289c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjM0MzYsIm5iZiI6MTcyOTUyMzEzNiwicGF0aCI6Ii84OTAyMTExOS8zNzg0NTY2MjgtZjYxYzk3NzktODc1Yi00OTNjLTg5ODQtZDRhZjU3Mjg5YzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE1MDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5M2JlOTZjNTYwOGNhYTE4ZTI4MjViYWU1OGYzNzRhZGQxYzFhODc0MmJmMWI1NjcyODMyOGU0NjJhYTI1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B2t3lveGcBVIRjfkIrha4Y4qJCQYNeHNClLalqFQItA)

Please @corneliusroemer. I would appreciate consideration of this lineage that is now visible in GISAID.

**Comment by ammaraziz** [comment]
@Vjimenez-vasquez Sorry for the delay. I'm volunteering to help the mpox designation team with these proposals. 

Any luck with getting permission to upload sequences to genbank? We (Australia) have seen a single B.1.6, but as there are little publicly available data it's been hard to pinpoint where it starts.

![image](https://github.com/user-attachments/assets/e5afab9f-5b6b-4063-8e6a-5b56893a2b88)

**Comment by ammaraziz** [comment]
There's also a possibility that Peru sequences contain more sublinages.

**Comment by corneliusroemer** [comment]
Thanks everyone!

Dropping the most recent (collected since 2023-01-01) Peruvian sequences from GISAID into Nextclade it looks pretty clear that there's one big sublineage, it's the same branch we see in the public sequences

<img width="1509" alt="Brave Browser 2024-10-27 16 44 12" src="https://github.com/user-attachments/assets/ae224db8-ed84-4755-a9e3-cd94d990c464">

<img width="1704" alt="Brave Browser 2024-10-27 16 41 30" src="https://github.com/user-attachments/assets/b23c3eac-3878-4d1d-8e4b-5cdd50f37c5f">

<img width="973" alt="Brave Browser 2024-10-27 16 41 34" src="https://github.com/user-attachments/assets/a03cb14e-824a-4f3a-80ae-f10d4f3434a0">

<img width="1619" alt="Brave Browser 2024-10-27 16 41 40" src="https://github.com/user-attachments/assets/7bce43f3-4283-43dd-a307-6c1698cc655e">

I think one could cut like this:

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/ef0cb707-0e85-4c31-8cc5-cf1a0dcf83e5">
