### ISSUE TITLE
Potential new hmpxv B.1* lineage (including sublineage) identified in Peru

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [mpxv-lineages/lineage-designation#9]
Hello everyone, I think this is the official site for hmpxv proposals, then I'm using the same pango-lineage format. This is the current observation.   

**Description**

Potential new hmpxv B.1* lineage identified in Peru and defined by mutation **G111029A** and a nested sub-clade defined by **G102694A**. Observation was conducted by the Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Genomes**
Earliest sequence: 2022-06-25
Most recent sequence: 2022-07-24

**Countries circulating**
Major clade: Peru, 65
Minor clade (sub-clade) : Peru, 6
[Major_clade.txt](https://github.com/mpxv-lineages/lineage-designation/files/9366180/Major_clade.txt)
[Minor_clade.txt](https://github.com/mpxv-lineages/lineage-designation/files/9366182/Minor_clade.txt)

**Evidence**
**Major Clade**
![peru_1](https://user-images.githubusercontent.com/89874227/185246875-5ac2db4c-dff1-48ba-9850-3af3dc436a67.jpg)

**Minor Clade**
![peru_2](https://user-images.githubusercontent.com/89874227/185246881-b33156d5-64c0-4ace-b081-5f6f0799f424.jpg)

**Comment by AngieHinrichs** [comment]
@Vjimenez-vasquez I believe this is the place!  😃 

Instead of EPI_ISL identifiers, can you provide INSDC accessions for sequences in this lineage?  Note the [README](https://github.com/mpxv-lineages/lineage-designation/blob/master/README.md) for this repository lists as a requirement "has at least one freely available high quality reference sequence" -- and sequences from GISAID (even analyses of sequences from GISAID) are not completely freely available.  For example, a FASTA sequence from INSDC could be included in a github repository like this one, or in a tool for identifying lineages of new MPXV sequences, but a sequence from GISAID cannot be included because it must remain on GISAID's website and on the private computers of GISAID members who are able to download the sequence from GISAID.

I was going to suggest using https://nextstrain.org/monkeypox/hmpxv1?d=tree&m=div&p=full and coloring by genotype to find sequences from this proposed lineage, but I see that will not work at the moment because no INSDC sequences (yet) have G111029A.  🙁  Would you and your coauthors consider depositing sequences to an INSDC member databse ([GenBank](https://submit.ncbi.nlm.nih.gov/about/bankit/), [ENA](https://ena-docs.readthedocs.io/en/latest/submit/assembly/genome.html), [DDBJ](https://www.ddbj.nig.ac.jp/ddbj/genome-e.html))?  GISAID imports monkeypox sequences from INSDC, so it would not be necessary to submit to both databases.

**Comment by Vjimenez-vasquez** [comment]
Hi @AngieHinrichs. Thanks for the quick reply. We currently have deposited 82 hMPXV genome sequences. But sure, I think we can submit this information to NCBI too.

**Comment by rneher** [comment]
Thanks so much, @Vjimenez-vasquez !

I believe this lineage has not been seen outside of Peru at this point, but given the uneven sampling it is likely present elsewhere as well. It seems to represent the majority of Peruvian cases and it would thus be useful to have it designated to facilitate spotting it elsewhere. As Angie outlines, we require that the clade is represented in sequences that can be freely shared. Let us know once genomes are up! (they should show up in nextstrain within 24h).

**Comment by AngieHinrichs** [comment]
@Vjimenez-vasquez, so glad you're willing to submit to GenBank too!  @corneliusroemer has made a [guide](https://docs.google.com/document/d/19rCUbqQQcWd3ICkg0-i73iP80gDaQX_BKE3qcIRJUng/edit?usp=sharing) to using the BankIt interface in case that helps.

**Comment by emmahodcroft** [comment]
Hi @Vjimenez-vasquez! I just wanted to update you - we saw the sequences from Peru come through on NCBI and are really grateful for your and your group sharing them. With this, we plan to designate this lineage as B.1.6 - you can see the PR here: https://github.com/mpxv-lineages/lineage-designation/pull/13

Peru's been absolutely fantastic in their monkeypox work - in case detection and in sequencing. Congratulations on this and thank you for your efforts, and for sharing your sequences! 🙏 🙌

**Comment by Vjimenez-vasquez** [comment]
> Hi @Vjimenez-vasquez! I just wanted to update you - we saw the sequences from Peru come through on NCBI and are really grateful for your and your group sharing them. With this, we plan to designate this lineage as B.1.6 - you can see the PR here: #13
> 
> Peru's been absolutely fantastic in their monkeypox work - in case detection and in sequencing. Congratulations on this and thank you for your efforts, and for sharing your sequences! 🙏 🙌

Thanks @emmahodcroft. We are really glad with this designation. We, the Genomic Surveillance Team of the Instituto Nacional de Salud (INS) Peru, are working very hard to study the dispersion of hMPXV in our country.
